// AUTO-GENERATED MASTER WRAPPER
// Project: llama.cpp  
// Generated by Pure ZSH C/C++ API Extractor
// Wed Aug 13 06:33:43 PM EDT 2025

#ifndef UNIVERSAL_WRAPPER_H
#define UNIVERSAL_WRAPPER_H

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// SYSTEM INCLUDES
// ============================================================================
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
}
#endif

#endif // UNIVERSAL_WRAPPER_H
