# pkg-env.conf

[shell]
bash
zsh

[dm]
GDM
SDDM
LightDM
LXDM
XDM

[session]
gnome
x11
wayland
kde_plasma
xfce
i3

[composite]
mutter
kwin_x11
kwin_wayland
compton
picom
Hyprland
Sway
weston

[fun]
neofetch
fortune
cowsay
matrix