/* automatically generated by rust-bindgen 0.72.0 */

pub const ggml_type_GGML_TYPE_F32: ggml_type = 0;
pub const ggml_type_GGML_TYPE_F16: ggml_type = 1;
pub const ggml_type_GGML_TYPE_Q4_0: ggml_type = 2;
pub const ggml_type_GGML_TYPE_Q4_1: ggml_type = 3;
pub const ggml_type_GGML_TYPE_Q5_0: ggml_type = 6;
pub const ggml_type_GGML_TYPE_Q5_1: ggml_type = 7;
pub const ggml_type_GGML_TYPE_Q8_0: ggml_type = 8;
pub const ggml_type_GGML_TYPE_Q8_1: ggml_type = 9;
pub const ggml_type_GGML_TYPE_Q2_K: ggml_type = 10;
pub const ggml_type_GGML_TYPE_Q3_K: ggml_type = 11;
pub const ggml_type_GGML_TYPE_Q4_K: ggml_type = 12;
pub const ggml_type_GGML_TYPE_Q5_K: ggml_type = 13;
pub const ggml_type_GGML_TYPE_Q6_K: ggml_type = 14;
pub const ggml_type_GGML_TYPE_Q8_K: ggml_type = 15;
pub const ggml_type_GGML_TYPE_IQ2_XXS: ggml_type = 16;
pub const ggml_type_GGML_TYPE_IQ2_XS: ggml_type = 17;
pub const ggml_type_GGML_TYPE_IQ3_XXS: ggml_type = 18;
pub const ggml_type_GGML_TYPE_IQ1_S: ggml_type = 19;
pub const ggml_type_GGML_TYPE_IQ4_NL: ggml_type = 20;
pub const ggml_type_GGML_TYPE_IQ3_S: ggml_type = 21;
pub const ggml_type_GGML_TYPE_IQ2_S: ggml_type = 22;
pub const ggml_type_GGML_TYPE_IQ4_XS: ggml_type = 23;
pub const ggml_type_GGML_TYPE_I8: ggml_type = 24;
pub const ggml_type_GGML_TYPE_I16: ggml_type = 25;
pub const ggml_type_GGML_TYPE_I32: ggml_type = 26;
pub const ggml_type_GGML_TYPE_I64: ggml_type = 27;
pub const ggml_type_GGML_TYPE_F64: ggml_type = 28;
pub const ggml_type_GGML_TYPE_IQ1_M: ggml_type = 29;
pub const ggml_type_GGML_TYPE_BF16: ggml_type = 30;
pub const ggml_type_GGML_TYPE_TQ1_0: ggml_type = 34;
pub const ggml_type_GGML_TYPE_TQ2_0: ggml_type = 35;
pub const ggml_type_GGML_TYPE_COUNT: ggml_type = 39;
pub type ggml_type = ::std::os::raw::c_uint;
pub const ggml_op_GGML_OP_NONE: ggml_op = 0;
pub const ggml_op_GGML_OP_DUP: ggml_op = 1;
pub const ggml_op_GGML_OP_ADD: ggml_op = 2;
pub const ggml_op_GGML_OP_ADD1: ggml_op = 3;
pub const ggml_op_GGML_OP_ACC: ggml_op = 4;
pub const ggml_op_GGML_OP_SUB: ggml_op = 5;
pub const ggml_op_GGML_OP_MUL: ggml_op = 6;
pub const ggml_op_GGML_OP_DIV: ggml_op = 7;
pub const ggml_op_GGML_OP_SQR: ggml_op = 8;
pub const ggml_op_GGML_OP_SQRT: ggml_op = 9;
pub const ggml_op_GGML_OP_LOG: ggml_op = 10;
pub const ggml_op_GGML_OP_SIN: ggml_op = 11;
pub const ggml_op_GGML_OP_COS: ggml_op = 12;
pub const ggml_op_GGML_OP_SUM: ggml_op = 13;
pub const ggml_op_GGML_OP_SUM_ROWS: ggml_op = 14;
pub const ggml_op_GGML_OP_MEAN: ggml_op = 15;
pub const ggml_op_GGML_OP_ARGMAX: ggml_op = 16;
pub const ggml_op_GGML_OP_COUNT_EQUAL: ggml_op = 17;
pub const ggml_op_GGML_OP_REPEAT: ggml_op = 18;
pub const ggml_op_GGML_OP_REPEAT_BACK: ggml_op = 19;
pub const ggml_op_GGML_OP_CONCAT: ggml_op = 20;
pub const ggml_op_GGML_OP_SILU_BACK: ggml_op = 21;
pub const ggml_op_GGML_OP_NORM: ggml_op = 22;
pub const ggml_op_GGML_OP_RMS_NORM: ggml_op = 23;
pub const ggml_op_GGML_OP_RMS_NORM_BACK: ggml_op = 24;
pub const ggml_op_GGML_OP_GROUP_NORM: ggml_op = 25;
pub const ggml_op_GGML_OP_L2_NORM: ggml_op = 26;
pub const ggml_op_GGML_OP_MUL_MAT: ggml_op = 27;
pub const ggml_op_GGML_OP_MUL_MAT_ID: ggml_op = 28;
pub const ggml_op_GGML_OP_OUT_PROD: ggml_op = 29;
pub const ggml_op_GGML_OP_SCALE: ggml_op = 30;
pub const ggml_op_GGML_OP_SET: ggml_op = 31;
pub const ggml_op_GGML_OP_CPY: ggml_op = 32;
pub const ggml_op_GGML_OP_CONT: ggml_op = 33;
pub const ggml_op_GGML_OP_RESHAPE: ggml_op = 34;
pub const ggml_op_GGML_OP_VIEW: ggml_op = 35;
pub const ggml_op_GGML_OP_PERMUTE: ggml_op = 36;
pub const ggml_op_GGML_OP_TRANSPOSE: ggml_op = 37;
pub const ggml_op_GGML_OP_GET_ROWS: ggml_op = 38;
pub const ggml_op_GGML_OP_GET_ROWS_BACK: ggml_op = 39;
pub const ggml_op_GGML_OP_SET_ROWS: ggml_op = 40;
pub const ggml_op_GGML_OP_DIAG: ggml_op = 41;
pub const ggml_op_GGML_OP_DIAG_MASK_INF: ggml_op = 42;
pub const ggml_op_GGML_OP_DIAG_MASK_ZERO: ggml_op = 43;
pub const ggml_op_GGML_OP_SOFT_MAX: ggml_op = 44;
pub const ggml_op_GGML_OP_SOFT_MAX_BACK: ggml_op = 45;
pub const ggml_op_GGML_OP_ROPE: ggml_op = 46;
pub const ggml_op_GGML_OP_ROPE_BACK: ggml_op = 47;
pub const ggml_op_GGML_OP_CLAMP: ggml_op = 48;
pub const ggml_op_GGML_OP_CONV_TRANSPOSE_1D: ggml_op = 49;
pub const ggml_op_GGML_OP_IM2COL: ggml_op = 50;
pub const ggml_op_GGML_OP_IM2COL_BACK: ggml_op = 51;
pub const ggml_op_GGML_OP_CONV_2D: ggml_op = 52;
pub const ggml_op_GGML_OP_CONV_2D_DW: ggml_op = 53;
pub const ggml_op_GGML_OP_CONV_TRANSPOSE_2D: ggml_op = 54;
pub const ggml_op_GGML_OP_POOL_1D: ggml_op = 55;
pub const ggml_op_GGML_OP_POOL_2D: ggml_op = 56;
pub const ggml_op_GGML_OP_POOL_2D_BACK: ggml_op = 57;
pub const ggml_op_GGML_OP_UPSCALE: ggml_op = 58;
pub const ggml_op_GGML_OP_PAD: ggml_op = 59;
pub const ggml_op_GGML_OP_PAD_REFLECT_1D: ggml_op = 60;
pub const ggml_op_GGML_OP_ROLL: ggml_op = 61;
pub const ggml_op_GGML_OP_ARANGE: ggml_op = 62;
pub const ggml_op_GGML_OP_TIMESTEP_EMBEDDING: ggml_op = 63;
pub const ggml_op_GGML_OP_ARGSORT: ggml_op = 64;
pub const ggml_op_GGML_OP_LEAKY_RELU: ggml_op = 65;
pub const ggml_op_GGML_OP_FLASH_ATTN_EXT: ggml_op = 66;
pub const ggml_op_GGML_OP_FLASH_ATTN_BACK: ggml_op = 67;
pub const ggml_op_GGML_OP_SSM_CONV: ggml_op = 68;
pub const ggml_op_GGML_OP_SSM_SCAN: ggml_op = 69;
pub const ggml_op_GGML_OP_WIN_PART: ggml_op = 70;
pub const ggml_op_GGML_OP_WIN_UNPART: ggml_op = 71;
pub const ggml_op_GGML_OP_GET_REL_POS: ggml_op = 72;
pub const ggml_op_GGML_OP_ADD_REL_POS: ggml_op = 73;
pub const ggml_op_GGML_OP_RWKV_WKV6: ggml_op = 74;
pub const ggml_op_GGML_OP_GATED_LINEAR_ATTN: ggml_op = 75;
pub const ggml_op_GGML_OP_RWKV_WKV7: ggml_op = 76;
pub const ggml_op_GGML_OP_UNARY: ggml_op = 77;
pub const ggml_op_GGML_OP_MAP_CUSTOM1: ggml_op = 78;
pub const ggml_op_GGML_OP_MAP_CUSTOM2: ggml_op = 79;
pub const ggml_op_GGML_OP_MAP_CUSTOM3: ggml_op = 80;
pub const ggml_op_GGML_OP_CUSTOM: ggml_op = 81;
pub const ggml_op_GGML_OP_CROSS_ENTROPY_LOSS: ggml_op = 82;
pub const ggml_op_GGML_OP_CROSS_ENTROPY_LOSS_BACK: ggml_op = 83;
pub const ggml_op_GGML_OP_OPT_STEP_ADAMW: ggml_op = 84;
pub const ggml_op_GGML_OP_GLU: ggml_op = 85;
pub const ggml_op_GGML_OP_COUNT: ggml_op = 86;
pub type ggml_op = ::std::os::raw::c_uint;
pub const ggml_log_level_GGML_LOG_LEVEL_NONE: ggml_log_level = 0;
pub const ggml_log_level_GGML_LOG_LEVEL_DEBUG: ggml_log_level = 1;
pub const ggml_log_level_GGML_LOG_LEVEL_INFO: ggml_log_level = 2;
pub const ggml_log_level_GGML_LOG_LEVEL_WARN: ggml_log_level = 3;
pub const ggml_log_level_GGML_LOG_LEVEL_ERROR: ggml_log_level = 4;
pub const ggml_log_level_GGML_LOG_LEVEL_CONT: ggml_log_level = 5;
pub type ggml_log_level = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_tensor {
    pub type_: ggml_type,
    pub buffer: *mut ggml_backend_buffer,
    pub ne: [i64; 4usize],
    pub nb: [usize; 4usize],
    pub op: ggml_op,
    pub op_params: [i32; 16usize],
    pub flags: i32,
    pub src: [*mut ggml_tensor; 10usize],
    pub view_src: *mut ggml_tensor,
    pub view_offs: usize,
    pub data: *mut ::std::os::raw::c_void,
    pub name: [::std::os::raw::c_char; 64usize],
    pub extra: *mut ::std::os::raw::c_void,
    pub padding: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ggml_tensor"][::std::mem::size_of::<ggml_tensor>() - 336usize];
    ["Alignment of ggml_tensor"][::std::mem::align_of::<ggml_tensor>() - 8usize];
    ["Offset of field: ggml_tensor::type_"][::std::mem::offset_of!(ggml_tensor, type_) - 0usize];
    ["Offset of field: ggml_tensor::buffer"][::std::mem::offset_of!(ggml_tensor, buffer) - 8usize];
    ["Offset of field: ggml_tensor::ne"][::std::mem::offset_of!(ggml_tensor, ne) - 16usize];
    ["Offset of field: ggml_tensor::nb"][::std::mem::offset_of!(ggml_tensor, nb) - 48usize];
    ["Offset of field: ggml_tensor::op"][::std::mem::offset_of!(ggml_tensor, op) - 80usize];
    ["Offset of field: ggml_tensor::op_params"]
        [::std::mem::offset_of!(ggml_tensor, op_params) - 84usize];
    ["Offset of field: ggml_tensor::flags"][::std::mem::offset_of!(ggml_tensor, flags) - 148usize];
    ["Offset of field: ggml_tensor::src"][::std::mem::offset_of!(ggml_tensor, src) - 152usize];
    ["Offset of field: ggml_tensor::view_src"]
        [::std::mem::offset_of!(ggml_tensor, view_src) - 232usize];
    ["Offset of field: ggml_tensor::view_offs"]
        [::std::mem::offset_of!(ggml_tensor, view_offs) - 240usize];
    ["Offset of field: ggml_tensor::data"][::std::mem::offset_of!(ggml_tensor, data) - 248usize];
    ["Offset of field: ggml_tensor::name"][::std::mem::offset_of!(ggml_tensor, name) - 256usize];
    ["Offset of field: ggml_tensor::extra"][::std::mem::offset_of!(ggml_tensor, extra) - 320usize];
    ["Offset of field: ggml_tensor::padding"]
        [::std::mem::offset_of!(ggml_tensor, padding) - 328usize];
};
pub type ggml_abort_callback =
    ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>;
pub type ggml_log_callback = ::std::option::Option<
    unsafe extern "C" fn(
        level: ggml_log_level,
        text: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_threadpool {
    _unused: [u8; 0],
}
pub type ggml_threadpool_t = *mut ggml_threadpool;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_backend_buffer_type {
    _unused: [u8; 0],
}
pub type ggml_backend_buffer_type_t = *mut ggml_backend_buffer_type;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_backend_device {
    _unused: [u8; 0],
}
pub type ggml_backend_dev_t = *mut ggml_backend_device;
pub type ggml_backend_sched_eval_callback = ::std::option::Option<
    unsafe extern "C" fn(
        t: *mut ggml_tensor,
        ask: bool,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_DISABLED: ggml_numa_strategy = 0;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_DISTRIBUTE: ggml_numa_strategy = 1;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_ISOLATE: ggml_numa_strategy = 2;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_NUMACTL: ggml_numa_strategy = 3;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_MIRROR: ggml_numa_strategy = 4;
pub const ggml_numa_strategy_GGML_NUMA_STRATEGY_COUNT: ggml_numa_strategy = 5;
pub type ggml_numa_strategy = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_opt_dataset {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_opt_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_opt_result {
    _unused: [u8; 0],
}
pub type ggml_opt_dataset_t = *mut ggml_opt_dataset;
pub type ggml_opt_context_t = *mut ggml_opt_context;
pub type ggml_opt_result_t = *mut ggml_opt_result;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_opt_optimizer_params {
    pub adamw: ggml_opt_optimizer_params__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_opt_optimizer_params__bindgen_ty_1 {
    pub alpha: f32,
    pub beta1: f32,
    pub beta2: f32,
    pub eps: f32,
    pub wd: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ggml_opt_optimizer_params__bindgen_ty_1"]
        [::std::mem::size_of::<ggml_opt_optimizer_params__bindgen_ty_1>() - 20usize];
    ["Alignment of ggml_opt_optimizer_params__bindgen_ty_1"]
        [::std::mem::align_of::<ggml_opt_optimizer_params__bindgen_ty_1>() - 4usize];
    ["Offset of field: ggml_opt_optimizer_params__bindgen_ty_1::alpha"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params__bindgen_ty_1, alpha) - 0usize];
    ["Offset of field: ggml_opt_optimizer_params__bindgen_ty_1::beta1"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params__bindgen_ty_1, beta1) - 4usize];
    ["Offset of field: ggml_opt_optimizer_params__bindgen_ty_1::beta2"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params__bindgen_ty_1, beta2) - 8usize];
    ["Offset of field: ggml_opt_optimizer_params__bindgen_ty_1::eps"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params__bindgen_ty_1, eps) - 12usize];
    ["Offset of field: ggml_opt_optimizer_params__bindgen_ty_1::wd"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params__bindgen_ty_1, wd) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ggml_opt_optimizer_params"]
        [::std::mem::size_of::<ggml_opt_optimizer_params>() - 20usize];
    ["Alignment of ggml_opt_optimizer_params"]
        [::std::mem::align_of::<ggml_opt_optimizer_params>() - 4usize];
    ["Offset of field: ggml_opt_optimizer_params::adamw"]
        [::std::mem::offset_of!(ggml_opt_optimizer_params, adamw) - 0usize];
};
pub type ggml_opt_get_optimizer_params = ::std::option::Option<
    unsafe extern "C" fn(userdata: *mut ::std::os::raw::c_void) -> ggml_opt_optimizer_params,
>;
pub type ggml_opt_epoch_callback = ::std::option::Option<
    unsafe extern "C" fn(
        train: bool,
        opt_ctx: ggml_opt_context_t,
        dataset: ggml_opt_dataset_t,
        result: ggml_opt_result_t,
        ibatch: i64,
        ibatch_max: i64,
        t_start_us: i64,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_vocab {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_model {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_memory_i {
    _unused: [u8; 0],
}
pub type llama_memory_t = *mut llama_memory_i;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_kv_cache {
    _unused: [u8; 0],
}
pub type llama_pos = i32;
pub type llama_token = i32;
pub type llama_seq_id = i32;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_NONE: llama_vocab_type = 0;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_SPM: llama_vocab_type = 1;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_BPE: llama_vocab_type = 2;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_WPM: llama_vocab_type = 3;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_UGM: llama_vocab_type = 4;
pub const llama_vocab_type_LLAMA_VOCAB_TYPE_RWKV: llama_vocab_type = 5;
pub type llama_vocab_type = ::std::os::raw::c_uint;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_DEFAULT: llama_vocab_pre_type = 0;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_LLAMA3: llama_vocab_pre_type = 1;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_DEEPSEEK_LLM: llama_vocab_pre_type = 2;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_DEEPSEEK_CODER: llama_vocab_pre_type = 3;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_FALCON: llama_vocab_pre_type = 4;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_MPT: llama_vocab_pre_type = 5;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_STARCODER: llama_vocab_pre_type = 6;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_GPT2: llama_vocab_pre_type = 7;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_REFACT: llama_vocab_pre_type = 8;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_COMMAND_R: llama_vocab_pre_type = 9;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_STABLELM2: llama_vocab_pre_type = 10;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_QWEN2: llama_vocab_pre_type = 11;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_OLMO: llama_vocab_pre_type = 12;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_DBRX: llama_vocab_pre_type = 13;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_SMAUG: llama_vocab_pre_type = 14;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_PORO: llama_vocab_pre_type = 15;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_CHATGLM3: llama_vocab_pre_type = 16;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_CHATGLM4: llama_vocab_pre_type = 17;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_VIKING: llama_vocab_pre_type = 18;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_JAIS: llama_vocab_pre_type = 19;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_TEKKEN: llama_vocab_pre_type = 20;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_SMOLLM: llama_vocab_pre_type = 21;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_CODESHELL: llama_vocab_pre_type = 22;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_BLOOM: llama_vocab_pre_type = 23;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_GPT3_FINNISH: llama_vocab_pre_type = 24;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_EXAONE: llama_vocab_pre_type = 25;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_CHAMELEON: llama_vocab_pre_type = 26;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_MINERVA: llama_vocab_pre_type = 27;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_DEEPSEEK3_LLM: llama_vocab_pre_type = 28;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_GPT4O: llama_vocab_pre_type = 29;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_SUPERBPE: llama_vocab_pre_type = 30;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_TRILLION: llama_vocab_pre_type = 31;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_BAILINGMOE: llama_vocab_pre_type = 32;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_LLAMA4: llama_vocab_pre_type = 33;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_PIXTRAL: llama_vocab_pre_type = 34;
pub const llama_vocab_pre_type_LLAMA_VOCAB_PRE_TYPE_SEED_CODER: llama_vocab_pre_type = 35;
pub type llama_vocab_pre_type = ::std::os::raw::c_uint;
pub const llama_rope_type_LLAMA_ROPE_TYPE_NONE: llama_rope_type = -1;
pub const llama_rope_type_LLAMA_ROPE_TYPE_NORM: llama_rope_type = 0;
pub const llama_rope_type_LLAMA_ROPE_TYPE_NEOX: llama_rope_type = 2;
pub const llama_rope_type_LLAMA_ROPE_TYPE_MROPE: llama_rope_type = 8;
pub const llama_rope_type_LLAMA_ROPE_TYPE_VISION: llama_rope_type = 24;
pub type llama_rope_type = ::std::os::raw::c_int;
pub const llama_token_type_LLAMA_TOKEN_TYPE_UNDEFINED: llama_token_type = 0;
pub const llama_token_type_LLAMA_TOKEN_TYPE_NORMAL: llama_token_type = 1;
pub const llama_token_type_LLAMA_TOKEN_TYPE_UNKNOWN: llama_token_type = 2;
pub const llama_token_type_LLAMA_TOKEN_TYPE_CONTROL: llama_token_type = 3;
pub const llama_token_type_LLAMA_TOKEN_TYPE_USER_DEFINED: llama_token_type = 4;
pub const llama_token_type_LLAMA_TOKEN_TYPE_UNUSED: llama_token_type = 5;
pub const llama_token_type_LLAMA_TOKEN_TYPE_BYTE: llama_token_type = 6;
pub type llama_token_type = ::std::os::raw::c_uint;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_UNDEFINED: llama_token_attr = 0;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_UNKNOWN: llama_token_attr = 1;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_UNUSED: llama_token_attr = 2;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_NORMAL: llama_token_attr = 4;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_CONTROL: llama_token_attr = 8;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_USER_DEFINED: llama_token_attr = 16;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_BYTE: llama_token_attr = 32;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_NORMALIZED: llama_token_attr = 64;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_LSTRIP: llama_token_attr = 128;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_RSTRIP: llama_token_attr = 256;
pub const llama_token_attr_LLAMA_TOKEN_ATTR_SINGLE_WORD: llama_token_attr = 512;
pub type llama_token_attr = ::std::os::raw::c_uint;
pub const llama_ftype_LLAMA_FTYPE_ALL_F32: llama_ftype = 0;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_F16: llama_ftype = 1;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q4_0: llama_ftype = 2;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q4_1: llama_ftype = 3;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q8_0: llama_ftype = 7;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q5_0: llama_ftype = 8;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q5_1: llama_ftype = 9;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q2_K: llama_ftype = 10;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q3_K_S: llama_ftype = 11;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q3_K_M: llama_ftype = 12;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q3_K_L: llama_ftype = 13;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q4_K_S: llama_ftype = 14;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q4_K_M: llama_ftype = 15;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q5_K_S: llama_ftype = 16;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q5_K_M: llama_ftype = 17;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q6_K: llama_ftype = 18;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ2_XXS: llama_ftype = 19;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ2_XS: llama_ftype = 20;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_Q2_K_S: llama_ftype = 21;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ3_XS: llama_ftype = 22;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ3_XXS: llama_ftype = 23;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ1_S: llama_ftype = 24;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ4_NL: llama_ftype = 25;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ3_S: llama_ftype = 26;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ3_M: llama_ftype = 27;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ2_S: llama_ftype = 28;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ2_M: llama_ftype = 29;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ4_XS: llama_ftype = 30;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_IQ1_M: llama_ftype = 31;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_BF16: llama_ftype = 32;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_TQ1_0: llama_ftype = 36;
pub const llama_ftype_LLAMA_FTYPE_MOSTLY_TQ2_0: llama_ftype = 37;
pub const llama_ftype_LLAMA_FTYPE_GUESSED: llama_ftype = 1024;
pub type llama_ftype = ::std::os::raw::c_uint;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED: llama_rope_scaling_type = -1;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_NONE: llama_rope_scaling_type = 0;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_LINEAR: llama_rope_scaling_type = 1;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_YARN: llama_rope_scaling_type = 2;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_LONGROPE: llama_rope_scaling_type = 3;
pub const llama_rope_scaling_type_LLAMA_ROPE_SCALING_TYPE_MAX_VALUE: llama_rope_scaling_type = 3;
pub type llama_rope_scaling_type = ::std::os::raw::c_int;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_UNSPECIFIED: llama_pooling_type = -1;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_NONE: llama_pooling_type = 0;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_MEAN: llama_pooling_type = 1;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_CLS: llama_pooling_type = 2;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_LAST: llama_pooling_type = 3;
pub const llama_pooling_type_LLAMA_POOLING_TYPE_RANK: llama_pooling_type = 4;
pub type llama_pooling_type = ::std::os::raw::c_int;
pub const llama_attention_type_LLAMA_ATTENTION_TYPE_UNSPECIFIED: llama_attention_type = -1;
pub const llama_attention_type_LLAMA_ATTENTION_TYPE_CAUSAL: llama_attention_type = 0;
pub const llama_attention_type_LLAMA_ATTENTION_TYPE_NON_CAUSAL: llama_attention_type = 1;
pub type llama_attention_type = ::std::os::raw::c_int;
pub const llama_split_mode_LLAMA_SPLIT_MODE_NONE: llama_split_mode = 0;
pub const llama_split_mode_LLAMA_SPLIT_MODE_LAYER: llama_split_mode = 1;
pub const llama_split_mode_LLAMA_SPLIT_MODE_ROW: llama_split_mode = 2;
pub type llama_split_mode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_token_data {
    pub id: llama_token,
    pub logit: f32,
    pub p: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_token_data"][::std::mem::size_of::<llama_token_data>() - 12usize];
    ["Alignment of llama_token_data"][::std::mem::align_of::<llama_token_data>() - 4usize];
    ["Offset of field: llama_token_data::id"]
        [::std::mem::offset_of!(llama_token_data, id) - 0usize];
    ["Offset of field: llama_token_data::logit"]
        [::std::mem::offset_of!(llama_token_data, logit) - 4usize];
    ["Offset of field: llama_token_data::p"][::std::mem::offset_of!(llama_token_data, p) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_token_data_array {
    pub data: *mut llama_token_data,
    pub size: usize,
    pub selected: i64,
    pub sorted: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_token_data_array"][::std::mem::size_of::<llama_token_data_array>() - 32usize];
    ["Alignment of llama_token_data_array"]
        [::std::mem::align_of::<llama_token_data_array>() - 8usize];
    ["Offset of field: llama_token_data_array::data"]
        [::std::mem::offset_of!(llama_token_data_array, data) - 0usize];
    ["Offset of field: llama_token_data_array::size"]
        [::std::mem::offset_of!(llama_token_data_array, size) - 8usize];
    ["Offset of field: llama_token_data_array::selected"]
        [::std::mem::offset_of!(llama_token_data_array, selected) - 16usize];
    ["Offset of field: llama_token_data_array::sorted"]
        [::std::mem::offset_of!(llama_token_data_array, sorted) - 24usize];
};
pub type llama_progress_callback = ::std::option::Option<
    unsafe extern "C" fn(progress: f32, user_data: *mut ::std::os::raw::c_void) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_batch {
    pub n_tokens: i32,
    pub token: *mut llama_token,
    pub embd: *mut f32,
    pub pos: *mut llama_pos,
    pub n_seq_id: *mut i32,
    pub seq_id: *mut *mut llama_seq_id,
    pub logits: *mut i8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_batch"][::std::mem::size_of::<llama_batch>() - 56usize];
    ["Alignment of llama_batch"][::std::mem::align_of::<llama_batch>() - 8usize];
    ["Offset of field: llama_batch::n_tokens"]
        [::std::mem::offset_of!(llama_batch, n_tokens) - 0usize];
    ["Offset of field: llama_batch::token"][::std::mem::offset_of!(llama_batch, token) - 8usize];
    ["Offset of field: llama_batch::embd"][::std::mem::offset_of!(llama_batch, embd) - 16usize];
    ["Offset of field: llama_batch::pos"][::std::mem::offset_of!(llama_batch, pos) - 24usize];
    ["Offset of field: llama_batch::n_seq_id"]
        [::std::mem::offset_of!(llama_batch, n_seq_id) - 32usize];
    ["Offset of field: llama_batch::seq_id"][::std::mem::offset_of!(llama_batch, seq_id) - 40usize];
    ["Offset of field: llama_batch::logits"][::std::mem::offset_of!(llama_batch, logits) - 48usize];
};
pub const llama_model_kv_override_type_LLAMA_KV_OVERRIDE_TYPE_INT: llama_model_kv_override_type = 0;
pub const llama_model_kv_override_type_LLAMA_KV_OVERRIDE_TYPE_FLOAT: llama_model_kv_override_type =
    1;
pub const llama_model_kv_override_type_LLAMA_KV_OVERRIDE_TYPE_BOOL: llama_model_kv_override_type =
    2;
pub const llama_model_kv_override_type_LLAMA_KV_OVERRIDE_TYPE_STR: llama_model_kv_override_type = 3;
pub type llama_model_kv_override_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct llama_model_kv_override {
    pub tag: llama_model_kv_override_type,
    pub key: [::std::os::raw::c_char; 128usize],
    pub __bindgen_anon_1: llama_model_kv_override__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union llama_model_kv_override__bindgen_ty_1 {
    pub val_i64: i64,
    pub val_f64: f64,
    pub val_bool: bool,
    pub val_str: [::std::os::raw::c_char; 128usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_model_kv_override__bindgen_ty_1"]
        [::std::mem::size_of::<llama_model_kv_override__bindgen_ty_1>() - 128usize];
    ["Alignment of llama_model_kv_override__bindgen_ty_1"]
        [::std::mem::align_of::<llama_model_kv_override__bindgen_ty_1>() - 8usize];
    ["Offset of field: llama_model_kv_override__bindgen_ty_1::val_i64"]
        [::std::mem::offset_of!(llama_model_kv_override__bindgen_ty_1, val_i64) - 0usize];
    ["Offset of field: llama_model_kv_override__bindgen_ty_1::val_f64"]
        [::std::mem::offset_of!(llama_model_kv_override__bindgen_ty_1, val_f64) - 0usize];
    ["Offset of field: llama_model_kv_override__bindgen_ty_1::val_bool"]
        [::std::mem::offset_of!(llama_model_kv_override__bindgen_ty_1, val_bool) - 0usize];
    ["Offset of field: llama_model_kv_override__bindgen_ty_1::val_str"]
        [::std::mem::offset_of!(llama_model_kv_override__bindgen_ty_1, val_str) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_model_kv_override"]
        [::std::mem::size_of::<llama_model_kv_override>() - 264usize];
    ["Alignment of llama_model_kv_override"]
        [::std::mem::align_of::<llama_model_kv_override>() - 8usize];
    ["Offset of field: llama_model_kv_override::tag"]
        [::std::mem::offset_of!(llama_model_kv_override, tag) - 0usize];
    ["Offset of field: llama_model_kv_override::key"]
        [::std::mem::offset_of!(llama_model_kv_override, key) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_model_tensor_buft_override {
    pub pattern: *const ::std::os::raw::c_char,
    pub buft: ggml_backend_buffer_type_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_model_tensor_buft_override"]
        [::std::mem::size_of::<llama_model_tensor_buft_override>() - 16usize];
    ["Alignment of llama_model_tensor_buft_override"]
        [::std::mem::align_of::<llama_model_tensor_buft_override>() - 8usize];
    ["Offset of field: llama_model_tensor_buft_override::pattern"]
        [::std::mem::offset_of!(llama_model_tensor_buft_override, pattern) - 0usize];
    ["Offset of field: llama_model_tensor_buft_override::buft"]
        [::std::mem::offset_of!(llama_model_tensor_buft_override, buft) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_model_params {
    pub devices: *mut ggml_backend_dev_t,
    pub tensor_buft_overrides: *const llama_model_tensor_buft_override,
    pub n_gpu_layers: i32,
    pub split_mode: llama_split_mode,
    pub main_gpu: i32,
    pub tensor_split: *const f32,
    pub progress_callback: llama_progress_callback,
    pub progress_callback_user_data: *mut ::std::os::raw::c_void,
    pub kv_overrides: *const llama_model_kv_override,
    pub vocab_only: bool,
    pub use_mmap: bool,
    pub use_mlock: bool,
    pub check_tensors: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_model_params"][::std::mem::size_of::<llama_model_params>() - 72usize];
    ["Alignment of llama_model_params"][::std::mem::align_of::<llama_model_params>() - 8usize];
    ["Offset of field: llama_model_params::devices"]
        [::std::mem::offset_of!(llama_model_params, devices) - 0usize];
    ["Offset of field: llama_model_params::tensor_buft_overrides"]
        [::std::mem::offset_of!(llama_model_params, tensor_buft_overrides) - 8usize];
    ["Offset of field: llama_model_params::n_gpu_layers"]
        [::std::mem::offset_of!(llama_model_params, n_gpu_layers) - 16usize];
    ["Offset of field: llama_model_params::split_mode"]
        [::std::mem::offset_of!(llama_model_params, split_mode) - 20usize];
    ["Offset of field: llama_model_params::main_gpu"]
        [::std::mem::offset_of!(llama_model_params, main_gpu) - 24usize];
    ["Offset of field: llama_model_params::tensor_split"]
        [::std::mem::offset_of!(llama_model_params, tensor_split) - 32usize];
    ["Offset of field: llama_model_params::progress_callback"]
        [::std::mem::offset_of!(llama_model_params, progress_callback) - 40usize];
    ["Offset of field: llama_model_params::progress_callback_user_data"]
        [::std::mem::offset_of!(llama_model_params, progress_callback_user_data) - 48usize];
    ["Offset of field: llama_model_params::kv_overrides"]
        [::std::mem::offset_of!(llama_model_params, kv_overrides) - 56usize];
    ["Offset of field: llama_model_params::vocab_only"]
        [::std::mem::offset_of!(llama_model_params, vocab_only) - 64usize];
    ["Offset of field: llama_model_params::use_mmap"]
        [::std::mem::offset_of!(llama_model_params, use_mmap) - 65usize];
    ["Offset of field: llama_model_params::use_mlock"]
        [::std::mem::offset_of!(llama_model_params, use_mlock) - 66usize];
    ["Offset of field: llama_model_params::check_tensors"]
        [::std::mem::offset_of!(llama_model_params, check_tensors) - 67usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_context_params {
    pub n_ctx: u32,
    pub n_batch: u32,
    pub n_ubatch: u32,
    pub n_seq_max: u32,
    pub n_threads: i32,
    pub n_threads_batch: i32,
    pub rope_scaling_type: llama_rope_scaling_type,
    pub pooling_type: llama_pooling_type,
    pub attention_type: llama_attention_type,
    pub rope_freq_base: f32,
    pub rope_freq_scale: f32,
    pub yarn_ext_factor: f32,
    pub yarn_attn_factor: f32,
    pub yarn_beta_fast: f32,
    pub yarn_beta_slow: f32,
    pub yarn_orig_ctx: u32,
    pub defrag_thold: f32,
    pub cb_eval: ggml_backend_sched_eval_callback,
    pub cb_eval_user_data: *mut ::std::os::raw::c_void,
    pub type_k: ggml_type,
    pub type_v: ggml_type,
    pub abort_callback: ggml_abort_callback,
    pub abort_callback_data: *mut ::std::os::raw::c_void,
    pub embeddings: bool,
    pub offload_kqv: bool,
    pub flash_attn: bool,
    pub no_perf: bool,
    pub op_offload: bool,
    pub swa_full: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_context_params"][::std::mem::size_of::<llama_context_params>() - 120usize];
    ["Alignment of llama_context_params"][::std::mem::align_of::<llama_context_params>() - 8usize];
    ["Offset of field: llama_context_params::n_ctx"]
        [::std::mem::offset_of!(llama_context_params, n_ctx) - 0usize];
    ["Offset of field: llama_context_params::n_batch"]
        [::std::mem::offset_of!(llama_context_params, n_batch) - 4usize];
    ["Offset of field: llama_context_params::n_ubatch"]
        [::std::mem::offset_of!(llama_context_params, n_ubatch) - 8usize];
    ["Offset of field: llama_context_params::n_seq_max"]
        [::std::mem::offset_of!(llama_context_params, n_seq_max) - 12usize];
    ["Offset of field: llama_context_params::n_threads"]
        [::std::mem::offset_of!(llama_context_params, n_threads) - 16usize];
    ["Offset of field: llama_context_params::n_threads_batch"]
        [::std::mem::offset_of!(llama_context_params, n_threads_batch) - 20usize];
    ["Offset of field: llama_context_params::rope_scaling_type"]
        [::std::mem::offset_of!(llama_context_params, rope_scaling_type) - 24usize];
    ["Offset of field: llama_context_params::pooling_type"]
        [::std::mem::offset_of!(llama_context_params, pooling_type) - 28usize];
    ["Offset of field: llama_context_params::attention_type"]
        [::std::mem::offset_of!(llama_context_params, attention_type) - 32usize];
    ["Offset of field: llama_context_params::rope_freq_base"]
        [::std::mem::offset_of!(llama_context_params, rope_freq_base) - 36usize];
    ["Offset of field: llama_context_params::rope_freq_scale"]
        [::std::mem::offset_of!(llama_context_params, rope_freq_scale) - 40usize];
    ["Offset of field: llama_context_params::yarn_ext_factor"]
        [::std::mem::offset_of!(llama_context_params, yarn_ext_factor) - 44usize];
    ["Offset of field: llama_context_params::yarn_attn_factor"]
        [::std::mem::offset_of!(llama_context_params, yarn_attn_factor) - 48usize];
    ["Offset of field: llama_context_params::yarn_beta_fast"]
        [::std::mem::offset_of!(llama_context_params, yarn_beta_fast) - 52usize];
    ["Offset of field: llama_context_params::yarn_beta_slow"]
        [::std::mem::offset_of!(llama_context_params, yarn_beta_slow) - 56usize];
    ["Offset of field: llama_context_params::yarn_orig_ctx"]
        [::std::mem::offset_of!(llama_context_params, yarn_orig_ctx) - 60usize];
    ["Offset of field: llama_context_params::defrag_thold"]
        [::std::mem::offset_of!(llama_context_params, defrag_thold) - 64usize];
    ["Offset of field: llama_context_params::cb_eval"]
        [::std::mem::offset_of!(llama_context_params, cb_eval) - 72usize];
    ["Offset of field: llama_context_params::cb_eval_user_data"]
        [::std::mem::offset_of!(llama_context_params, cb_eval_user_data) - 80usize];
    ["Offset of field: llama_context_params::type_k"]
        [::std::mem::offset_of!(llama_context_params, type_k) - 88usize];
    ["Offset of field: llama_context_params::type_v"]
        [::std::mem::offset_of!(llama_context_params, type_v) - 92usize];
    ["Offset of field: llama_context_params::abort_callback"]
        [::std::mem::offset_of!(llama_context_params, abort_callback) - 96usize];
    ["Offset of field: llama_context_params::abort_callback_data"]
        [::std::mem::offset_of!(llama_context_params, abort_callback_data) - 104usize];
    ["Offset of field: llama_context_params::embeddings"]
        [::std::mem::offset_of!(llama_context_params, embeddings) - 112usize];
    ["Offset of field: llama_context_params::offload_kqv"]
        [::std::mem::offset_of!(llama_context_params, offload_kqv) - 113usize];
    ["Offset of field: llama_context_params::flash_attn"]
        [::std::mem::offset_of!(llama_context_params, flash_attn) - 114usize];
    ["Offset of field: llama_context_params::no_perf"]
        [::std::mem::offset_of!(llama_context_params, no_perf) - 115usize];
    ["Offset of field: llama_context_params::op_offload"]
        [::std::mem::offset_of!(llama_context_params, op_offload) - 116usize];
    ["Offset of field: llama_context_params::swa_full"]
        [::std::mem::offset_of!(llama_context_params, swa_full) - 117usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_model_quantize_params {
    pub nthread: i32,
    pub ftype: llama_ftype,
    pub output_tensor_type: ggml_type,
    pub token_embedding_type: ggml_type,
    pub allow_requantize: bool,
    pub quantize_output_tensor: bool,
    pub only_copy: bool,
    pub pure_: bool,
    pub keep_split: bool,
    pub imatrix: *mut ::std::os::raw::c_void,
    pub kv_overrides: *mut ::std::os::raw::c_void,
    pub tensor_types: *mut ::std::os::raw::c_void,
    pub prune_layers: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_model_quantize_params"]
        [::std::mem::size_of::<llama_model_quantize_params>() - 56usize];
    ["Alignment of llama_model_quantize_params"]
        [::std::mem::align_of::<llama_model_quantize_params>() - 8usize];
    ["Offset of field: llama_model_quantize_params::nthread"]
        [::std::mem::offset_of!(llama_model_quantize_params, nthread) - 0usize];
    ["Offset of field: llama_model_quantize_params::ftype"]
        [::std::mem::offset_of!(llama_model_quantize_params, ftype) - 4usize];
    ["Offset of field: llama_model_quantize_params::output_tensor_type"]
        [::std::mem::offset_of!(llama_model_quantize_params, output_tensor_type) - 8usize];
    ["Offset of field: llama_model_quantize_params::token_embedding_type"]
        [::std::mem::offset_of!(llama_model_quantize_params, token_embedding_type) - 12usize];
    ["Offset of field: llama_model_quantize_params::allow_requantize"]
        [::std::mem::offset_of!(llama_model_quantize_params, allow_requantize) - 16usize];
    ["Offset of field: llama_model_quantize_params::quantize_output_tensor"]
        [::std::mem::offset_of!(llama_model_quantize_params, quantize_output_tensor) - 17usize];
    ["Offset of field: llama_model_quantize_params::only_copy"]
        [::std::mem::offset_of!(llama_model_quantize_params, only_copy) - 18usize];
    ["Offset of field: llama_model_quantize_params::pure_"]
        [::std::mem::offset_of!(llama_model_quantize_params, pure_) - 19usize];
    ["Offset of field: llama_model_quantize_params::keep_split"]
        [::std::mem::offset_of!(llama_model_quantize_params, keep_split) - 20usize];
    ["Offset of field: llama_model_quantize_params::imatrix"]
        [::std::mem::offset_of!(llama_model_quantize_params, imatrix) - 24usize];
    ["Offset of field: llama_model_quantize_params::kv_overrides"]
        [::std::mem::offset_of!(llama_model_quantize_params, kv_overrides) - 32usize];
    ["Offset of field: llama_model_quantize_params::tensor_types"]
        [::std::mem::offset_of!(llama_model_quantize_params, tensor_types) - 40usize];
    ["Offset of field: llama_model_quantize_params::prune_layers"]
        [::std::mem::offset_of!(llama_model_quantize_params, prune_layers) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_logit_bias {
    pub token: llama_token,
    pub bias: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_logit_bias"][::std::mem::size_of::<llama_logit_bias>() - 8usize];
    ["Alignment of llama_logit_bias"][::std::mem::align_of::<llama_logit_bias>() - 4usize];
    ["Offset of field: llama_logit_bias::token"]
        [::std::mem::offset_of!(llama_logit_bias, token) - 0usize];
    ["Offset of field: llama_logit_bias::bias"]
        [::std::mem::offset_of!(llama_logit_bias, bias) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_sampler_chain_params {
    pub no_perf: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_sampler_chain_params"]
        [::std::mem::size_of::<llama_sampler_chain_params>() - 1usize];
    ["Alignment of llama_sampler_chain_params"]
        [::std::mem::align_of::<llama_sampler_chain_params>() - 1usize];
    ["Offset of field: llama_sampler_chain_params::no_perf"]
        [::std::mem::offset_of!(llama_sampler_chain_params, no_perf) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_chat_message {
    pub role: *const ::std::os::raw::c_char,
    pub content: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_chat_message"][::std::mem::size_of::<llama_chat_message>() - 16usize];
    ["Alignment of llama_chat_message"][::std::mem::align_of::<llama_chat_message>() - 8usize];
    ["Offset of field: llama_chat_message::role"]
        [::std::mem::offset_of!(llama_chat_message, role) - 0usize];
    ["Offset of field: llama_chat_message::content"]
        [::std::mem::offset_of!(llama_chat_message, content) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_adapter_lora {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn llama_model_default_params() -> llama_model_params;
}
unsafe extern "C" {
    pub fn llama_context_default_params() -> llama_context_params;
}
unsafe extern "C" {
    pub fn llama_sampler_chain_default_params() -> llama_sampler_chain_params;
}
unsafe extern "C" {
    pub fn llama_model_quantize_default_params() -> llama_model_quantize_params;
}
unsafe extern "C" {
    pub fn llama_backend_init();
}
unsafe extern "C" {
    pub fn llama_backend_free();
}
unsafe extern "C" {
    pub fn llama_numa_init(numa: ggml_numa_strategy);
}
unsafe extern "C" {
    pub fn llama_attach_threadpool(
        ctx: *mut llama_context,
        threadpool: ggml_threadpool_t,
        threadpool_batch: ggml_threadpool_t,
    );
}
unsafe extern "C" {
    pub fn llama_detach_threadpool(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_load_model_from_file(
        path_model: *const ::std::os::raw::c_char,
        params: llama_model_params,
    ) -> *mut llama_model;
}
unsafe extern "C" {
    pub fn llama_model_load_from_file(
        path_model: *const ::std::os::raw::c_char,
        params: llama_model_params,
    ) -> *mut llama_model;
}
unsafe extern "C" {
    pub fn llama_model_load_from_splits(
        paths: *mut *const ::std::os::raw::c_char,
        n_paths: usize,
        params: llama_model_params,
    ) -> *mut llama_model;
}
unsafe extern "C" {
    pub fn llama_model_save_to_file(
        model: *const llama_model,
        path_model: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn llama_free_model(model: *mut llama_model);
}
unsafe extern "C" {
    pub fn llama_model_free(model: *mut llama_model);
}
unsafe extern "C" {
    pub fn llama_init_from_model(
        model: *mut llama_model,
        params: llama_context_params,
    ) -> *mut llama_context;
}
unsafe extern "C" {
    pub fn llama_new_context_with_model(
        model: *mut llama_model,
        params: llama_context_params,
    ) -> *mut llama_context;
}
unsafe extern "C" {
    pub fn llama_free(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_time_us() -> i64;
}
unsafe extern "C" {
    pub fn llama_max_devices() -> usize;
}
unsafe extern "C" {
    pub fn llama_max_parallel_sequences() -> usize;
}
unsafe extern "C" {
    pub fn llama_supports_mmap() -> bool;
}
unsafe extern "C" {
    pub fn llama_supports_mlock() -> bool;
}
unsafe extern "C" {
    pub fn llama_supports_gpu_offload() -> bool;
}
unsafe extern "C" {
    pub fn llama_supports_rpc() -> bool;
}
unsafe extern "C" {
    pub fn llama_n_ctx(ctx: *const llama_context) -> u32;
}
unsafe extern "C" {
    pub fn llama_n_batch(ctx: *const llama_context) -> u32;
}
unsafe extern "C" {
    pub fn llama_n_ubatch(ctx: *const llama_context) -> u32;
}
unsafe extern "C" {
    pub fn llama_n_seq_max(ctx: *const llama_context) -> u32;
}
unsafe extern "C" {
    pub fn llama_n_ctx_train(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_n_embd(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_n_layer(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_n_head(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_n_vocab(vocab: *const llama_vocab) -> i32;
}
unsafe extern "C" {
    pub fn llama_get_model(ctx: *const llama_context) -> *const llama_model;
}
unsafe extern "C" {
    pub fn llama_get_memory(ctx: *const llama_context) -> llama_memory_t;
}
unsafe extern "C" {
    pub fn llama_pooling_type(ctx: *const llama_context) -> llama_pooling_type;
}
unsafe extern "C" {
    pub fn llama_get_kv_self(ctx: *mut llama_context) -> *mut llama_kv_cache;
}
unsafe extern "C" {
    pub fn llama_model_get_vocab(model: *const llama_model) -> *const llama_vocab;
}
unsafe extern "C" {
    pub fn llama_model_rope_type(model: *const llama_model) -> llama_rope_type;
}
unsafe extern "C" {
    pub fn llama_model_n_ctx_train(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_n_embd(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_n_layer(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_n_head(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_n_head_kv(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_n_swa(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_rope_freq_scale_train(model: *const llama_model) -> f32;
}
unsafe extern "C" {
    pub fn llama_model_n_cls_out(model: *const llama_model) -> u32;
}
unsafe extern "C" {
    pub fn llama_model_cls_label(
        model: *const llama_model,
        i: u32,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_vocab_type(vocab: *const llama_vocab) -> llama_vocab_type;
}
unsafe extern "C" {
    pub fn llama_vocab_n_tokens(vocab: *const llama_vocab) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_meta_val_str(
        model: *const llama_model,
        key: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_meta_count(model: *const llama_model) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_meta_key_by_index(
        model: *const llama_model,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_meta_val_str_by_index(
        model: *const llama_model,
        i: i32,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_desc(
        model: *const llama_model,
        buf: *mut ::std::os::raw::c_char,
        buf_size: usize,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_model_size(model: *const llama_model) -> u64;
}
unsafe extern "C" {
    pub fn llama_model_chat_template(
        model: *const llama_model,
        name: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_model_n_params(model: *const llama_model) -> u64;
}
unsafe extern "C" {
    pub fn llama_model_has_encoder(model: *const llama_model) -> bool;
}
unsafe extern "C" {
    pub fn llama_model_has_decoder(model: *const llama_model) -> bool;
}
unsafe extern "C" {
    pub fn llama_model_decoder_start_token(model: *const llama_model) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_model_is_recurrent(model: *const llama_model) -> bool;
}
unsafe extern "C" {
    pub fn llama_model_quantize(
        fname_inp: *const ::std::os::raw::c_char,
        fname_out: *const ::std::os::raw::c_char,
        params: *const llama_model_quantize_params,
    ) -> u32;
}
unsafe extern "C" {
    pub fn llama_adapter_lora_init(
        model: *mut llama_model,
        path_lora: *const ::std::os::raw::c_char,
    ) -> *mut llama_adapter_lora;
}
unsafe extern "C" {
    pub fn llama_adapter_lora_free(adapter: *mut llama_adapter_lora);
}
unsafe extern "C" {
    pub fn llama_set_adapter_lora(
        ctx: *mut llama_context,
        adapter: *mut llama_adapter_lora,
        scale: f32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_rm_adapter_lora(ctx: *mut llama_context, adapter: *mut llama_adapter_lora) -> i32;
}
unsafe extern "C" {
    pub fn llama_clear_adapter_lora(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_apply_adapter_cvec(
        ctx: *mut llama_context,
        data: *const f32,
        len: usize,
        n_embd: i32,
        il_start: i32,
        il_end: i32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_memory_clear(mem: llama_memory_t, data: bool);
}
unsafe extern "C" {
    pub fn llama_memory_seq_rm(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_memory_seq_cp(
        mem: llama_memory_t,
        seq_id_src: llama_seq_id,
        seq_id_dst: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    );
}
unsafe extern "C" {
    pub fn llama_memory_seq_keep(mem: llama_memory_t, seq_id: llama_seq_id);
}
unsafe extern "C" {
    pub fn llama_memory_seq_add(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        delta: llama_pos,
    );
}
unsafe extern "C" {
    pub fn llama_memory_seq_div(
        mem: llama_memory_t,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        d: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn llama_memory_seq_pos_min(mem: llama_memory_t, seq_id: llama_seq_id) -> llama_pos;
}
unsafe extern "C" {
    pub fn llama_memory_seq_pos_max(mem: llama_memory_t, seq_id: llama_seq_id) -> llama_pos;
}
unsafe extern "C" {
    pub fn llama_memory_can_shift(mem: llama_memory_t) -> bool;
}
unsafe extern "C" {
    pub fn llama_kv_self_n_tokens(ctx: *const llama_context) -> i32;
}
unsafe extern "C" {
    pub fn llama_kv_self_used_cells(ctx: *const llama_context) -> i32;
}
unsafe extern "C" {
    pub fn llama_kv_self_clear(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_rm(
        ctx: *mut llama_context,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_cp(
        ctx: *mut llama_context,
        seq_id_src: llama_seq_id,
        seq_id_dst: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
    );
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_keep(ctx: *mut llama_context, seq_id: llama_seq_id);
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_add(
        ctx: *mut llama_context,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        delta: llama_pos,
    );
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_div(
        ctx: *mut llama_context,
        seq_id: llama_seq_id,
        p0: llama_pos,
        p1: llama_pos,
        d: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_pos_min(ctx: *mut llama_context, seq_id: llama_seq_id) -> llama_pos;
}
unsafe extern "C" {
    pub fn llama_kv_self_seq_pos_max(ctx: *mut llama_context, seq_id: llama_seq_id) -> llama_pos;
}
unsafe extern "C" {
    pub fn llama_kv_self_defrag(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_kv_self_can_shift(ctx: *const llama_context) -> bool;
}
unsafe extern "C" {
    pub fn llama_kv_self_update(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_state_get_size(ctx: *mut llama_context) -> usize;
}
unsafe extern "C" {
    pub fn llama_get_state_size(ctx: *mut llama_context) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_get_data(ctx: *mut llama_context, dst: *mut u8, size: usize) -> usize;
}
unsafe extern "C" {
    pub fn llama_copy_state_data(ctx: *mut llama_context, dst: *mut u8) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_set_data(ctx: *mut llama_context, src: *const u8, size: usize) -> usize;
}
unsafe extern "C" {
    pub fn llama_set_state_data(ctx: *mut llama_context, src: *const u8) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_load_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_load_session_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_state_save_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_save_session_file(
        ctx: *mut llama_context,
        path_session: *const ::std::os::raw::c_char,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn llama_state_seq_get_size(ctx: *mut llama_context, seq_id: llama_seq_id) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_seq_get_data(
        ctx: *mut llama_context,
        dst: *mut u8,
        size: usize,
        seq_id: llama_seq_id,
    ) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_seq_set_data(
        ctx: *mut llama_context,
        src: *const u8,
        size: usize,
        dest_seq_id: llama_seq_id,
    ) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_seq_save_file(
        ctx: *mut llama_context,
        filepath: *const ::std::os::raw::c_char,
        seq_id: llama_seq_id,
        tokens: *const llama_token,
        n_token_count: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn llama_state_seq_load_file(
        ctx: *mut llama_context,
        filepath: *const ::std::os::raw::c_char,
        dest_seq_id: llama_seq_id,
        tokens_out: *mut llama_token,
        n_token_capacity: usize,
        n_token_count_out: *mut usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn llama_batch_get_one(tokens: *mut llama_token, n_tokens: i32) -> llama_batch;
}
unsafe extern "C" {
    pub fn llama_batch_init(n_tokens: i32, embd: i32, n_seq_max: i32) -> llama_batch;
}
unsafe extern "C" {
    pub fn llama_batch_free(batch: llama_batch);
}
unsafe extern "C" {
    pub fn llama_encode(ctx: *mut llama_context, batch: llama_batch) -> i32;
}
unsafe extern "C" {
    pub fn llama_decode(ctx: *mut llama_context, batch: llama_batch) -> i32;
}
unsafe extern "C" {
    pub fn llama_set_n_threads(ctx: *mut llama_context, n_threads: i32, n_threads_batch: i32);
}
unsafe extern "C" {
    pub fn llama_n_threads(ctx: *mut llama_context) -> i32;
}
unsafe extern "C" {
    pub fn llama_n_threads_batch(ctx: *mut llama_context) -> i32;
}
unsafe extern "C" {
    pub fn llama_set_embeddings(ctx: *mut llama_context, embeddings: bool);
}
unsafe extern "C" {
    pub fn llama_set_causal_attn(ctx: *mut llama_context, causal_attn: bool);
}
unsafe extern "C" {
    pub fn llama_set_warmup(ctx: *mut llama_context, warmup: bool);
}
unsafe extern "C" {
    pub fn llama_set_abort_callback(
        ctx: *mut llama_context,
        abort_callback: ggml_abort_callback,
        abort_callback_data: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn llama_synchronize(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_get_logits(ctx: *mut llama_context) -> *mut f32;
}
unsafe extern "C" {
    pub fn llama_get_logits_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
unsafe extern "C" {
    pub fn llama_get_embeddings(ctx: *mut llama_context) -> *mut f32;
}
unsafe extern "C" {
    pub fn llama_get_embeddings_ith(ctx: *mut llama_context, i: i32) -> *mut f32;
}
unsafe extern "C" {
    pub fn llama_get_embeddings_seq(ctx: *mut llama_context, seq_id: llama_seq_id) -> *mut f32;
}
unsafe extern "C" {
    pub fn llama_vocab_get_text(
        vocab: *const llama_vocab,
        token: llama_token,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_vocab_get_score(vocab: *const llama_vocab, token: llama_token) -> f32;
}
unsafe extern "C" {
    pub fn llama_vocab_get_attr(vocab: *const llama_vocab, token: llama_token) -> llama_token_attr;
}
unsafe extern "C" {
    pub fn llama_vocab_is_eog(vocab: *const llama_vocab, token: llama_token) -> bool;
}
unsafe extern "C" {
    pub fn llama_vocab_is_control(vocab: *const llama_vocab, token: llama_token) -> bool;
}
unsafe extern "C" {
    pub fn llama_vocab_bos(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_eos(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_eot(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_sep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_nl(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_pad(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_get_add_bos(vocab: *const llama_vocab) -> bool;
}
unsafe extern "C" {
    pub fn llama_vocab_get_add_eos(vocab: *const llama_vocab) -> bool;
}
unsafe extern "C" {
    pub fn llama_vocab_get_add_sep(vocab: *const llama_vocab) -> bool;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_pre(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_suf(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_mid(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_pad(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_rep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_fim_sep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_get_text(
        vocab: *const llama_vocab,
        token: llama_token,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_token_get_score(vocab: *const llama_vocab, token: llama_token) -> f32;
}
unsafe extern "C" {
    pub fn llama_token_get_attr(vocab: *const llama_vocab, token: llama_token) -> llama_token_attr;
}
unsafe extern "C" {
    pub fn llama_token_is_eog(vocab: *const llama_vocab, token: llama_token) -> bool;
}
unsafe extern "C" {
    pub fn llama_token_is_control(vocab: *const llama_vocab, token: llama_token) -> bool;
}
unsafe extern "C" {
    pub fn llama_token_bos(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_eos(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_eot(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_cls(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_sep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_nl(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_pad(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_add_bos_token(vocab: *const llama_vocab) -> bool;
}
unsafe extern "C" {
    pub fn llama_add_eos_token(vocab: *const llama_vocab) -> bool;
}
unsafe extern "C" {
    pub fn llama_token_fim_pre(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_fim_suf(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_fim_mid(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_fim_pad(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_fim_rep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_token_fim_sep(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    pub fn llama_vocab_cls(vocab: *const llama_vocab) -> llama_token;
}
unsafe extern "C" {
    #[doc = " @details Convert the provided text into tokens.\n @param tokens The tokens pointer must be large enough to hold the resulting tokens.\n @return Returns the number of tokens on success, no more than n_tokens_max\n @return Returns a negative number on failure - the number of tokens that would have been returned\n @return Returns INT32_MIN on overflow (e.g., tokenization result size exceeds int32_t limit)\n @param add_special Allow to add BOS and EOS tokens if model is configured to do so.\n @param parse_special Allow tokenizing special and/or control tokens which otherwise are not exposed and treated\n                      as plaintext. Does not insert a leading space."]
    pub fn llama_tokenize(
        vocab: *const llama_vocab,
        text: *const ::std::os::raw::c_char,
        text_len: i32,
        tokens: *mut llama_token,
        n_tokens_max: i32,
        add_special: bool,
        parse_special: bool,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_token_to_piece(
        vocab: *const llama_vocab,
        token: llama_token,
        buf: *mut ::std::os::raw::c_char,
        length: i32,
        lstrip: i32,
        special: bool,
    ) -> i32;
}
unsafe extern "C" {
    #[doc = " @details Convert the provided tokens into text (inverse of llama_tokenize()).\n @param text The char pointer must be large enough to hold the resulting text.\n @return Returns the number of chars/bytes on success, no more than text_len_max.\n @return Returns a negative number on failure - the number of chars/bytes that would have been returned.\n @param remove_special Allow to remove BOS and EOS tokens if model is configured to do so.\n @param unparse_special If true, special tokens are rendered in the output."]
    pub fn llama_detokenize(
        vocab: *const llama_vocab,
        tokens: *const llama_token,
        n_tokens: i32,
        text: *mut ::std::os::raw::c_char,
        text_len_max: i32,
        remove_special: bool,
        unparse_special: bool,
    ) -> i32;
}
unsafe extern "C" {
    #[doc = " Apply chat template. Inspired by hf apply_chat_template() on python.\n Both \"model\" and \"custom_template\" are optional, but at least one is required. \"custom_template\" has higher precedence than \"model\"\n NOTE: This function does not use a jinja parser. It only support a pre-defined list of template. See more: https://github.com/ggml-org/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template\n @param tmpl A Jinja template to use for this chat. If this is nullptr, the model’s default chat template will be used instead.\n @param chat Pointer to a list of multiple llama_chat_message\n @param n_msg Number of llama_chat_message in this chat\n @param add_ass Whether to end the prompt with the token(s) that indicate the start of an assistant message.\n @param buf A buffer to hold the output formatted prompt. The recommended alloc size is 2 * (total number of characters of all messages)\n @param length The size of the allocated buffer\n @return The total number of bytes of the formatted prompt. If is it larger than the size of buffer, you may need to re-alloc it and then re-apply the template."]
    pub fn llama_chat_apply_template(
        tmpl: *const ::std::os::raw::c_char,
        chat: *const llama_chat_message,
        n_msg: usize,
        add_ass: bool,
        buf: *mut ::std::os::raw::c_char,
        length: i32,
    ) -> i32;
}
unsafe extern "C" {
    pub fn llama_chat_builtin_templates(
        output: *mut *const ::std::os::raw::c_char,
        len: usize,
    ) -> i32;
}
pub type llama_sampler_context_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_sampler_i {
    pub name: ::std::option::Option<
        unsafe extern "C" fn(smpl: *const llama_sampler) -> *const ::std::os::raw::c_char,
    >,
    pub accept:
        ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler, token: llama_token)>,
    pub apply: ::std::option::Option<
        unsafe extern "C" fn(smpl: *mut llama_sampler, cur_p: *mut llama_token_data_array),
    >,
    pub reset: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
    pub clone: ::std::option::Option<
        unsafe extern "C" fn(smpl: *const llama_sampler) -> *mut llama_sampler,
    >,
    pub free: ::std::option::Option<unsafe extern "C" fn(smpl: *mut llama_sampler)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_sampler_i"][::std::mem::size_of::<llama_sampler_i>() - 48usize];
    ["Alignment of llama_sampler_i"][::std::mem::align_of::<llama_sampler_i>() - 8usize];
    ["Offset of field: llama_sampler_i::name"]
        [::std::mem::offset_of!(llama_sampler_i, name) - 0usize];
    ["Offset of field: llama_sampler_i::accept"]
        [::std::mem::offset_of!(llama_sampler_i, accept) - 8usize];
    ["Offset of field: llama_sampler_i::apply"]
        [::std::mem::offset_of!(llama_sampler_i, apply) - 16usize];
    ["Offset of field: llama_sampler_i::reset"]
        [::std::mem::offset_of!(llama_sampler_i, reset) - 24usize];
    ["Offset of field: llama_sampler_i::clone"]
        [::std::mem::offset_of!(llama_sampler_i, clone) - 32usize];
    ["Offset of field: llama_sampler_i::free"]
        [::std::mem::offset_of!(llama_sampler_i, free) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_sampler {
    pub iface: *const llama_sampler_i,
    pub ctx: llama_sampler_context_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_sampler"][::std::mem::size_of::<llama_sampler>() - 16usize];
    ["Alignment of llama_sampler"][::std::mem::align_of::<llama_sampler>() - 8usize];
    ["Offset of field: llama_sampler::iface"]
        [::std::mem::offset_of!(llama_sampler, iface) - 0usize];
    ["Offset of field: llama_sampler::ctx"][::std::mem::offset_of!(llama_sampler, ctx) - 8usize];
};
unsafe extern "C" {
    pub fn llama_sampler_init(
        iface: *const llama_sampler_i,
        ctx: llama_sampler_context_t,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_name(smpl: *const llama_sampler) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_sampler_accept(smpl: *mut llama_sampler, token: llama_token);
}
unsafe extern "C" {
    pub fn llama_sampler_apply(smpl: *mut llama_sampler, cur_p: *mut llama_token_data_array);
}
unsafe extern "C" {
    pub fn llama_sampler_reset(smpl: *mut llama_sampler);
}
unsafe extern "C" {
    pub fn llama_sampler_clone(smpl: *const llama_sampler) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_free(smpl: *mut llama_sampler);
}
unsafe extern "C" {
    pub fn llama_sampler_chain_init(params: llama_sampler_chain_params) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_chain_add(chain: *mut llama_sampler, smpl: *mut llama_sampler);
}
unsafe extern "C" {
    pub fn llama_sampler_chain_get(chain: *const llama_sampler, i: i32) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_chain_n(chain: *const llama_sampler) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn llama_sampler_chain_remove(chain: *mut llama_sampler, i: i32) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_init_greedy() -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_init_dist(seed: u32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Sorts candidate tokens by their logits in descending order and calculate probabilities based on logits.\n NOTE: Avoid using on the full vocabulary as the sorting can become slow. For example, apply top-k or top-p sampling first."]
    pub fn llama_sampler_init_softmax() -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Top-K sampling described in academic paper \"The Curious Case of Neural Text Degeneration\" https://arxiv.org/abs/1904.09751\n Setting k <= 0 makes this a noop"]
    pub fn llama_sampler_init_top_k(k: i32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Nucleus sampling described in academic paper \"The Curious Case of Neural Text Degeneration\" https://arxiv.org/abs/1904.09751"]
    pub fn llama_sampler_init_top_p(p: f32, min_keep: usize) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Minimum P sampling as described in https://github.com/ggml-org/llama.cpp/pull/3841"]
    pub fn llama_sampler_init_min_p(p: f32, min_keep: usize) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Locally Typical Sampling implementation described in the paper https://arxiv.org/abs/2202.00666."]
    pub fn llama_sampler_init_typical(p: f32, min_keep: usize) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " #details Updates the logits l_i` = l_i/t. When t <= 0.0f, the maximum logit is kept at it's original value, the rest are set to -inf"]
    pub fn llama_sampler_init_temp(t: f32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Dynamic temperature implementation (a.k.a. entropy) described in the paper https://arxiv.org/abs/2309.02772."]
    pub fn llama_sampler_init_temp_ext(t: f32, delta: f32, exponent: f32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details XTC sampler as described in https://github.com/oobabooga/text-generation-webui/pull/6335"]
    pub fn llama_sampler_init_xtc(p: f32, t: f32, min_keep: usize, seed: u32)
    -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Top n sigma sampling as described in academic paper \"Top-nσ: Not All Logits Are You Need\" https://arxiv.org/pdf/2411.07641"]
    pub fn llama_sampler_init_top_n_sigma(n: f32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Mirostat 1.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.\n @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.\n @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.\n @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.\n @param m The number of tokens considered in the estimation of `s_hat`. This is an arbitrary value that is used to calculate `s_hat`, which in turn helps to calculate the value of `k`. In the paper, they use `m = 100`, but you can experiment with different values to see how it affects the performance of the algorithm.\n @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal."]
    pub fn llama_sampler_init_mirostat(
        n_vocab: i32,
        seed: u32,
        tau: f32,
        eta: f32,
        m: i32,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Mirostat 2.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.\n @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.\n @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.\n @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.\n @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal."]
    pub fn llama_sampler_init_mirostat_v2(seed: u32, tau: f32, eta: f32) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Intializes a GBNF grammar, see grammars/README.md for details.\n @param vocab The vocabulary that this grammar will be used with.\n @param grammar_str The production rules for the grammar, encoded as a string. Returns an empty grammar if empty. Returns NULL if parsing of grammar_str fails.\n @param grammar_root The name of the start symbol for the grammar."]
    pub fn llama_sampler_init_grammar(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_init_grammar_lazy(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
        trigger_words: *mut *const ::std::os::raw::c_char,
        num_trigger_words: usize,
        trigger_tokens: *const llama_token,
        num_trigger_tokens: usize,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " @details Lazy grammar sampler, introduced in https://github.com/ggml-org/llama.cpp/pull/9639\n @param trigger_patterns A list of patterns that will trigger the grammar sampler. Pattern will be matched from the start of the generation output, and grammar sampler will be fed content starting from its first match group.\n @param trigger_tokens A list of tokens that will trigger the grammar sampler. Grammar sampler will be fed content starting from the trigger token included."]
    pub fn llama_sampler_init_grammar_lazy_patterns(
        vocab: *const llama_vocab,
        grammar_str: *const ::std::os::raw::c_char,
        grammar_root: *const ::std::os::raw::c_char,
        trigger_patterns: *mut *const ::std::os::raw::c_char,
        num_trigger_patterns: usize,
        trigger_tokens: *const llama_token,
        num_trigger_tokens: usize,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = " NOTE: Avoid using on the full vocabulary as searching for repeated tokens can become slow. For example, apply top-k or top-p sampling first."]
    pub fn llama_sampler_init_penalties(
        penalty_last_n: i32,
        penalty_repeat: f32,
        penalty_freq: f32,
        penalty_present: f32,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    #[doc = "  @details DRY sampler, designed by p-e-w, as described in: https://github.com/oobabooga/text-generation-webui/pull/5677, porting Koboldcpp implementation authored by pi6am: https://github.com/LostRuins/koboldcpp/pull/982"]
    pub fn llama_sampler_init_dry(
        vocab: *const llama_vocab,
        n_ctx_train: i32,
        dry_multiplier: f32,
        dry_base: f32,
        dry_allowed_length: i32,
        dry_penalty_last_n: i32,
        seq_breakers: *mut *const ::std::os::raw::c_char,
        num_breakers: usize,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_init_logit_bias(
        n_vocab: i32,
        n_logit_bias: i32,
        logit_bias: *const llama_logit_bias,
    ) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_init_infill(vocab: *const llama_vocab) -> *mut llama_sampler;
}
unsafe extern "C" {
    pub fn llama_sampler_get_seed(smpl: *const llama_sampler) -> u32;
}
unsafe extern "C" {
    pub fn llama_sampler_sample(
        smpl: *mut llama_sampler,
        ctx: *mut llama_context,
        idx: i32,
    ) -> llama_token;
}
unsafe extern "C" {
    #[doc = " @details Build a split GGUF final path for this chunk.\n          llama_split_path(split_path, sizeof(split_path), \"/models/ggml-model-q4_0\", 2, 4) => split_path = \"/models/ggml-model-q4_0-00002-of-00004.gguf\""]
    pub fn llama_split_path(
        split_path: *mut ::std::os::raw::c_char,
        maxlen: usize,
        path_prefix: *const ::std::os::raw::c_char,
        split_no: ::std::os::raw::c_int,
        split_count: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @details Extract the path prefix from the split_path if and only if the split_no and split_count match.\n          llama_split_prefix(split_prefix, 64, \"/models/ggml-model-q4_0-00002-of-00004.gguf\", 2, 4) => split_prefix = \"/models/ggml-model-q4_0\""]
    pub fn llama_split_prefix(
        split_prefix: *mut ::std::os::raw::c_char,
        maxlen: usize,
        split_path: *const ::std::os::raw::c_char,
        split_no: ::std::os::raw::c_int,
        split_count: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn llama_print_system_info() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn llama_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_perf_context_data {
    pub t_start_ms: f64,
    pub t_load_ms: f64,
    pub t_p_eval_ms: f64,
    pub t_eval_ms: f64,
    pub n_p_eval: i32,
    pub n_eval: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_perf_context_data"][::std::mem::size_of::<llama_perf_context_data>() - 40usize];
    ["Alignment of llama_perf_context_data"]
        [::std::mem::align_of::<llama_perf_context_data>() - 8usize];
    ["Offset of field: llama_perf_context_data::t_start_ms"]
        [::std::mem::offset_of!(llama_perf_context_data, t_start_ms) - 0usize];
    ["Offset of field: llama_perf_context_data::t_load_ms"]
        [::std::mem::offset_of!(llama_perf_context_data, t_load_ms) - 8usize];
    ["Offset of field: llama_perf_context_data::t_p_eval_ms"]
        [::std::mem::offset_of!(llama_perf_context_data, t_p_eval_ms) - 16usize];
    ["Offset of field: llama_perf_context_data::t_eval_ms"]
        [::std::mem::offset_of!(llama_perf_context_data, t_eval_ms) - 24usize];
    ["Offset of field: llama_perf_context_data::n_p_eval"]
        [::std::mem::offset_of!(llama_perf_context_data, n_p_eval) - 32usize];
    ["Offset of field: llama_perf_context_data::n_eval"]
        [::std::mem::offset_of!(llama_perf_context_data, n_eval) - 36usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_perf_sampler_data {
    pub t_sample_ms: f64,
    pub n_sample: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_perf_sampler_data"][::std::mem::size_of::<llama_perf_sampler_data>() - 16usize];
    ["Alignment of llama_perf_sampler_data"]
        [::std::mem::align_of::<llama_perf_sampler_data>() - 8usize];
    ["Offset of field: llama_perf_sampler_data::t_sample_ms"]
        [::std::mem::offset_of!(llama_perf_sampler_data, t_sample_ms) - 0usize];
    ["Offset of field: llama_perf_sampler_data::n_sample"]
        [::std::mem::offset_of!(llama_perf_sampler_data, n_sample) - 8usize];
};
unsafe extern "C" {
    pub fn llama_perf_context(ctx: *const llama_context) -> llama_perf_context_data;
}
unsafe extern "C" {
    pub fn llama_perf_context_print(ctx: *const llama_context);
}
unsafe extern "C" {
    pub fn llama_perf_context_reset(ctx: *mut llama_context);
}
unsafe extern "C" {
    pub fn llama_perf_sampler(chain: *const llama_sampler) -> llama_perf_sampler_data;
}
unsafe extern "C" {
    pub fn llama_perf_sampler_print(chain: *const llama_sampler);
}
unsafe extern "C" {
    pub fn llama_perf_sampler_reset(chain: *mut llama_sampler);
}
pub type llama_opt_param_filter = ::std::option::Option<
    unsafe extern "C" fn(tensor: *const ggml_tensor, userdata: *mut ::std::os::raw::c_void) -> bool,
>;
unsafe extern "C" {
    pub fn llama_opt_param_filter_all(
        tensor: *const ggml_tensor,
        userdata: *mut ::std::os::raw::c_void,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llama_opt_params {
    pub n_ctx_train: u32,
    pub param_filter: llama_opt_param_filter,
    pub param_filter_ud: *mut ::std::os::raw::c_void,
    pub get_opt_pars: ggml_opt_get_optimizer_params,
    pub get_opt_pars_ud: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llama_opt_params"][::std::mem::size_of::<llama_opt_params>() - 40usize];
    ["Alignment of llama_opt_params"][::std::mem::align_of::<llama_opt_params>() - 8usize];
    ["Offset of field: llama_opt_params::n_ctx_train"]
        [::std::mem::offset_of!(llama_opt_params, n_ctx_train) - 0usize];
    ["Offset of field: llama_opt_params::param_filter"]
        [::std::mem::offset_of!(llama_opt_params, param_filter) - 8usize];
    ["Offset of field: llama_opt_params::param_filter_ud"]
        [::std::mem::offset_of!(llama_opt_params, param_filter_ud) - 16usize];
    ["Offset of field: llama_opt_params::get_opt_pars"]
        [::std::mem::offset_of!(llama_opt_params, get_opt_pars) - 24usize];
    ["Offset of field: llama_opt_params::get_opt_pars_ud"]
        [::std::mem::offset_of!(llama_opt_params, get_opt_pars_ud) - 32usize];
};
unsafe extern "C" {
    pub fn llama_opt_init(
        lctx: *mut llama_context,
        model: *mut llama_model,
        lopt_params: llama_opt_params,
    );
}
unsafe extern "C" {
    pub fn llama_opt_epoch(
        lctx: *mut llama_context,
        dataset: ggml_opt_dataset_t,
        result_train: ggml_opt_result_t,
        result_eval: ggml_opt_result_t,
        idata_split: i64,
        callback_train: ggml_opt_epoch_callback,
        callback_eval: ggml_opt_epoch_callback,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_backend_buffer {
    pub _address: u8,
}
